<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7542" started-at="2018-06-01T07:20:28Z" finished-at="2018-06-01T07:20:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7542" started-at="2018-06-01T07:20:28Z" finished-at="2018-06-01T07:20:35Z">
      <class name="scripts123.Verfiy">
        <test-method status="PASS" signature="openapp()[pri:0, instance:scripts123.Verfiy@11758f2a]" name="openapp" is-config="true" duration-ms="7145" started-at="2018-06-01T07:20:28Z" finished-at="2018-06-01T07:20:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapp -->
        <test-method status="FAIL" signature="test3()[pri:0, instance:scripts123.Verfiy@11758f2a]" name="test3" duration-ms="7" started-at="2018-06-01T07:20:35Z" finished-at="2018-06-01T07:20:35Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
pwd12 cannot be resolved to a variable
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
pwd12 cannot be resolved to a variable

at scripts123.Verfiy.test3(Verfiy.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="closeapp()[pri:0, instance:scripts123.Verfiy@11758f2a]" name="closeapp" is-config="true" duration-ms="360" started-at="2018-06-01T07:20:35Z" finished-at="2018-06-01T07:20:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeapp -->
      </class> <!-- scripts123.Verfiy -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
